### ISSUE TITLE
devices.xylo.syns61201.XyloMonitor How can I use this Xylo monitor class? Is there any example? 

### ISSUE THREAD

**Issue by bbkrsddq1** [synsense/rockpool#11]
devices.xylo.syns61201.XyloMonitor How can I use this Xylo monitor class? Is there any example? 

I like to use my voice command to examine the performance of my deployed trained network to Xylo HDK using onboard Xylo Microphone. Can anyone help me with this?

**Comment by DylanMuir** [comment]
Basically, when you evolve a `XyloMonitor`, you get live output of the network in real-time. e.g.

```
mod = XyloMonitor(...)
out, _, _ = mod(np.zeros((T, 0)), record = False)
```

`out` will then contain the spiking outputs for `T` timesteps, recorded in real-time when you executed the evolution live of code. So if you want continuous inference, you need to repeatedly call `mod()` in a loop, with as little delay as possible. When building live demos, we often use multiprocessing and IPC queues to handle this.

BTW you should always use `record = False` (the default) for `XyloMonitor`, since you can't really record internal state while operating in real-time mode.

**Comment by DylanMuir** [comment]
Tutorial example here: https://rockpool.ai/devices/quick-xylo/xylo-audio-2-intro.html#Part-III:-Deploying-the-AFE-and-SNN-cores-in-free-running-inference-mode

**Comment by bbkrsddq11** [comment]
Thank you so much.
